services:
  nginx:
    image: nginx:latest
    container_name: bee_nginx
    ports:
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./static:/usr/share/nginx/html:ro
    depends_on:
      - app
      - api

  app:
    build:
      context: ./interface
      dockerfile: Dockerfile.app
    container_name: bee-app
    environment:
      - NODE_ENV=production
    volumes:
      - ./app:/usr/src/app
    ports:
      - "3000:3000"

  api:
    build:
      context: ./api
    container_name: bee-api
    environment:
      - DATABASE_URL=${POSTGRES_URL}
      - MONGO_URL=${MONGO_URL}
    volumes:
      - ./api:/usr/src/api
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
      - postgres

  mongodb:
    image: mongo:latest
    container_name: bee-mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"

  postgres:
    image: postgres:latest
    container_name: bee-postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  mongodb_data:
  postgres_data: