FROM python:3.12-bullseye

COPY . /api
COPY ./requirements-api.txt /api/requirements.txt

RUN pip install --no-cache-dir -r /api/requirements.txt

WORKDIR /api

CMD ["uvicorn", "back_workers:app", "--host", "0.0.0.0", "--port", "8000"]